kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-data
  namespace: web
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/tmp"
