kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name : dataclaim
  namespace: web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
