kind: PersistentVolume
apiVersion: v1
metadata:
  name: sql-data1
  namespace: sql
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/"
