kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: sql-set
  namespace: sql
spec:
  serviceName: sql-service
  replicas: 3
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql-cont
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sql-configmap
              key: MYSQL_DATABASE
        volumeMounts:
        - name: sql-data-vol
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: sql-data-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
